---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-patch
  namespace: system
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-patch-cluster-role
  namespace: system
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]

- apiGroups: [""]
  resources:
    - nodes/status
  verbs:
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-patch-cluster-role-binding
  namespace: system
subjects:
- kind: ServiceAccount
  name: node-patch
  namespace: system
roleRef:
  kind: ClusterRole
  name: node-patch-cluster-role
  apiGroup: rbac.authorization.k8s.io

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: system
  name: node-patch
  labels:
    app: node-patch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-patch
  template:
    metadata:
      labels:
        app: node-patch
    spec:
      containers:
      - name: node-patch
        image: tombokombo/podasr:final3
        volumeMounts:
        - name: node-patch
          mountPath: /etc/pod-as-resource/
        resources:
          requests:
            cpu: 100m
            memory: 100M
      serviceAccountName: node-patch
      volumes:
      - name: node-patch
        configMap:
          defaultMode: 420
          items:
          - key: config.yaml
            path: config.yaml
          name: node-patch

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-patch
  namespace: system
data:
  config.yaml: |
    tainttest: 2
